version: "3"
services:
  fluentd:
    image: abhiramabhi/fluentd
    volumes:
      - ./fluentd/:/fluentd/etc:ro
      - ./logs/:/var/log/fluent/
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"
        tag: nginx

  rewards-calculator-app:
    image: abhiramabhi/radix-rewards-calculator
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: any
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"
        tag: rewards

    command: npm start
