version: "3"
services:
  app:
    image: abhiramabhi/radix-rewards-calculator
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 15s
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    command: npm start

  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:3080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginxlogs/:/var/log/nginx/

