version: "3"
services:

  rewards-calculator-app:
    image: abhiramabhi/radix-rewards-calculator
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 15s
      #restart_policy:
       # condition: any
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        tag: rewards
    command: npm start

  fluentd:
    user: root
    image: abhiramabhi/fluentd
    volumes:
      - ./fluentd/:/fluentd/etc:ro
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      
  elasticsearch: # port 9200
    image: elasticsearch:8.4.3
    environment:
    - node.name=elasticsearch
    - cluster.initial_master_nodes=elasticsearch
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.9.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9300
      ELASTICSEARCH_HOSTS: http://elasticsearch:9300